name: trial_workflow   #name of worklow

on:                     # event trigger
  push:
    branches: [main]


jobs:
  build:                       #jobID-first job
    runs-on: ubuntu-latest    #runner for the job

    steps:
      - name: checkout code
        uses: actions/checkout@v6

  test:                        #jobID-second job
    runs-on: ubuntu-latest

    steps: 
      - name: print a statement
        run:  echo "second job"
    
    


 

  
