name: trial_workflow   #name of worklow

on:                     # event trigger
  push:
    branches: [main]


jobs:
  build:                       #jobID-first job
    name:  First Job
    runs-on: runner-1    #runner for the job
    needs: test
    

    steps:
      - name: checkout code
        uses: actions/checkout@v6

  test:                        #jobID-second job
    name: second job
    runs-on: ubuntu-latest
    
 

    steps: 
      - name: print a statement
        run:  echo "second job"
    
    


 

  
